
# Project name.
name: 'dbt_meta_testing'
version: '0.1.2'
config-version: 2

# The "profile" dbt uses for this project.
profile: 'dbt_meta_testing'

# Configuration paths.
source-paths: ["models"]
# source-paths: ["test_models"] # TO DO: Configure via scripts for integration testing
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:         
    - "target"
    - "dbt_modules"

# Configured for the logger macro.
vars:
    logging_level: INFO

# TO DO: Configure via scripts for integration testing
# models:
#   dbt_meta_testing:
#       # Applies to all files under models/example/
#       example:
#           +materialized: view
#           +required_tests: {'unique': 1, 'not_null': 2, 'mock_schema_test': 1}
#           +required_docs: true