
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_meta_testing'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_meta_testing'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!

source-paths: ["models"]
# source-paths: ["test_models"] # TO DO: Configure via scripts for integration testing
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# Configured for the logger macro.
vars:
    logging_level: INFO

# TO DO: Configure via scripts for integration testing
# models:
#   dbt_meta_testing:
#       # Applies to all files under models/example/
#       example:
#           +materialized: view
#           +required_tests: {'unique': 1, 'not_null': 2, 'mock_schema_test': 1}
#           +required_docs: true